default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: transactions

test:
  <<: *default
  database: transactions_test

production:
  <<: *default
  database: your_production_database_name
